server:
  port: 8088
spring:
  profiles:
    active: prod   #dev prod test  打包记得开启prod生产模式，这样子才有日志保存
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  jackson:
    default-property-inclusion: non_null
  mail:
    protocol: smtp
    host: smtp.exmail.qq.com
    default-encoding: UTF-8
    properties:
      smtp:
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:mapper/*.xml


attendance:
  term: '2023_2024_1'  #学期 1 2表示上下学期
  week: '2023-9-4'  #第一周星期一
  grade: 23
  path: ./logs
